export const dummyVideos = [
    {
        youtubeId: "abc123",
        title: "Learn JavaScript in 1 Hour",
        description: "A crash course to get started with JavaScript.",
        channelTitle: "CodeWithMosh",
        channelId: "mosh001",
        thumbnails: {
            default: "http://img.youtube.com/vi/abc123/default.jpg",
            medium: "http://img.youtube.com/vi/abc123/mqdefault.jpg",
            high: "http://img.youtube.com/vi/abc123/hqdefault.jpg"
        },
        tags: ["javascript", "beginner", "web dev"],
        category: "Education",
        publishedAt: new Date("2024-08-10T12:00:00Z"),
        duration: "PT60M0S",
        viewCount: 125000,
        likeCount: 8900,
        favoriteCount: 0,
        commentCount: 520,
        searchTerms: ["javascript", "mosh", "web development"],
        curated: false,
        addedBySearch: true,
    },
    {
        youtubeId: "def456",
        title: "React Hooks Explained",
        description: "A deep dive into React hooks and how to use them effectively.",
        channelTitle: "Huxn Dev",
        channelId: "huxn001",
        thumbnails: {
            default: "http://img.youtube.com/vi/def456/default.jpg",
            medium: "http://img.youtube.com/vi/def456/mqdefault.jpg",
            high: "http://img.youtube.com/vi/def456/hqdefault.jpg"
        },
        tags: ["react", "hooks", "useState", "useEffect"],
        category: "Education",
        publishedAt: new Date("2024-06-05T09:30:00Z"),
        duration: "PT25M30S",
        viewCount: 56000,
        likeCount: 3200,
        favoriteCount: 0,
        commentCount: 180,
        searchTerms: ["react", "react hooks", "web dev"],
        curated: true,
        addedBySearch: false,
    },
    {
        youtubeId: "ghi789",
        title: "Python Tutorial for Beginners",
        description: "Complete Python tutorial for absolute beginners.",
        channelTitle: "Programming with John",
        channelId: "john002",
        thumbnails: {
            default: "http://img.youtube.com/vi/ghi789/default.jpg",
            medium: "http://img.youtube.com/vi/ghi789/mqdefault.jpg",
            high: "http://img.youtube.com/vi/ghi789/hqdefault.jpg"
        },
        tags: ["python", "beginner", "programming"],
        category: "Education",
        publishedAt: new Date("2023-11-12T10:00:00Z"),
        duration: "PT45M10S",
        viewCount: 207000,
        likeCount: 15100,
        favoriteCount: 0,
        commentCount: 940,
        searchTerms: ["python", "programming", "tutorial"],
        curated: true,
        addedBySearch: true,
    },
    {
        youtubeId: "jkl101",
        title: "Node.js Crash Course",
        description: "Learn Node.js from scratch in this beginner-friendly course.",
        channelTitle: "Traversy Media",
        channelId: "traversy001",
        thumbnails: {
            default: "http://img.youtube.com/vi/jkl101/default.jpg",
            medium: "http://img.youtube.com/vi/jkl101/mqdefault.jpg",
            high: "http://img.youtube.com/vi/jkl101/hqdefault.jpg"
        },
        tags: ["nodejs", "backend", "javascript"],
        category: "Education",
        publishedAt: new Date("2024-02-15T08:00:00Z"),
        duration: "PT35M45S",
        viewCount: 89000,
        likeCount: 5200,
        favoriteCount: 0,
        commentCount: 300,
        searchTerms: ["nodejs", "backend", "javascript"],
        curated: false,
        addedBySearch: true,
    },
    {
        youtubeId: "mno202",
        title: "MongoDB Tutorial",
        description: "Master MongoDB for full stack web development.",
        channelTitle: "The Net Ninja",
        channelId: "netninja001",
        thumbnails: {
            default: "http://img.youtube.com/vi/mno202/default.jpg",
            medium: "http://img.youtube.com/vi/mno202/mqdefault.jpg",
            high: "http://img.youtube.com/vi/mno202/hqdefault.jpg"
        },
        tags: ["mongodb", "database", "nosql"],
        category: "Education",
        publishedAt: new Date("2024-03-08T13:00:00Z"),
        duration: "PT50M20S",
        viewCount: 41000,
        likeCount: 2400,
        favoriteCount: 0,
        commentCount: 210,
        searchTerms: ["mongodb", "database", "nosql"],
        curated: true,
        addedBySearch: true,
    },
    {
        youtubeId: "pqr303",
        title: "Express.js Basics",
        description: "How to use Express.js in Node apps.",
        channelTitle: "Academind",
        channelId: "academind001",
        thumbnails: {
            default: "http://img.youtube.com/vi/pqr303/default.jpg",
            medium: "http://img.youtube.com/vi/pqr303/mqdefault.jpg",
            high: "http://img.youtube.com/vi/pqr303/hqdefault.jpg"
        },
        tags: ["express", "nodejs", "api"],
        category: "Education",
        publishedAt: new Date("2024-04-12T16:00:00Z"),
        duration: "PT20M00S",
        viewCount: 35000,
        likeCount: 1800,
        favoriteCount: 0,
        commentCount: 90,
        searchTerms: ["express", "nodejs", "api"],
        curated: false,
        addedBySearch: true,
    },
    {
        youtubeId: "stu404",
        title: "Build a Full Stack App",
        description: "Learn how to build a MERN stack project from scratch.",
        channelTitle: "Codevolution",
        channelId: "codevo001",
        thumbnails: {
            default: "http://img.youtube.com/vi/stu404/default.jpg",
            medium: "http://img.youtube.com/vi/stu404/mqdefault.jpg",
            high: "http://img.youtube.com/vi/stu404/hqdefault.jpg"
        },
        tags: ["mern", "fullstack", "react", "node"],
        category: "Education",
        publishedAt: new Date("2024-01-28T11:00:00Z"),
        duration: "PT80M00S",
        viewCount: 102000,
        likeCount: 6700,
        favoriteCount: 0,
        commentCount: 430,
        searchTerms: ["mern", "full stack", "mongodb", "express", "react", "node"],
        curated: true,
        addedBySearch: false,
    },
    {
        youtubeId: "vwx505",
        title: "Tailwind CSS Tutorial",
        description: "Style your apps fast using Tailwind CSS.",
        channelTitle: "DesignCourse",
        channelId: "design001",
        thumbnails: {
            default: "http://img.youtube.com/vi/vwx505/default.jpg",
            medium: "http://img.youtube.com/vi/vwx505/mqdefault.jpg",
            high: "http://img.youtube.com/vi/vwx505/hqdefault.jpg"
        },
        tags: ["tailwind", "css", "design"],
        category: "Design",
        publishedAt: new Date("2024-05-05T14:00:00Z"),
        duration: "PT15M00S",
        viewCount: 28000,
        likeCount: 1100,
        favoriteCount: 0,
        commentCount: 60,
        searchTerms: ["tailwind", "css", "frontend"],
        curated: false,
        addedBySearch: true,
    },
    {
        youtubeId: "yza606",
        title: "Understanding Async/Await",
        description: "A quick tutorial on async/await in JavaScript.",
        channelTitle: "TechWorld with Nana",
        channelId: "nana001",
        thumbnails: {
            default: "http://img.youtube.com/vi/yza606/default.jpg",
            medium: "http://img.youtube.com/vi/yza606/mqdefault.jpg",
            high: "http://img.youtube.com/vi/yza606/hqdefault.jpg"
        },
        tags: ["javascript", "async", "await", "promises"],
        category: "Education",
        publishedAt: new Date("2024-07-07T17:00:00Z"),
        duration: "PT18M00S",
        viewCount: 47000,
        likeCount: 2100,
        favoriteCount: 0,
        commentCount: 160,
        searchTerms: ["javascript", "async", "await"],
        curated: false,
        addedBySearch: true,
    },
    {
        youtubeId: "bcd707",
        title: "Master Git in 30 Minutes",
        description: "Version control basics and Git fundamentals.",
        channelTitle: "Fireship",
        channelId: "fireship001",
        thumbnails: {
            default: "http://img.youtube.com/vi/bcd707/default.jpg",
            medium: "http://img.youtube.com/vi/bcd707/mqdefault.jpg",
            high: "http://img.youtube.com/vi/bcd707/hqdefault.jpg"
        },
        tags: ["git", "version control", "github"],
        category: "Tools",
        publishedAt: new Date("2024-09-09T19:00:00Z"),
        duration: "PT30M00S",
        viewCount: 78000,
        likeCount: 4100,
        favoriteCount: 0,
        commentCount: 250,
        searchTerms: ["git", "github", "version control"],
        curated: true,
        addedBySearch: false,
    }
];
